# Changes here will be overwritten by Copier
_commit: v3.6.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: hannes.hartmann@eccenca.com
author_name: Hannes Hartmann
github_page: ''
project_description: Create awesome Knowledge Graphs with eccenca Corporate Memory
    :-)
project_slug: mattermost
pypi: false

