---
version: "3"

services:
  mattermost:
    image: 'mattermost/mattermost-preview'
    ports:
      - '8065:8065'
    volumes:
      - "./volume1:/volume1"
    entrypoint:
      - "/volume1/docker-entry.sh"

