---
version: "3"

services:
  mattermost:
    image: 'mattermost/mattermost-preview'
    ports:
      - '8065:8065'
    volumes:
      - "cmem-plugin-mattermost/docker/volume:/volume"
    entrypoint:
      - "/volume/docker-entry.sh"