---
version: "3"

services:
  mattermost:
    image: 'mattermost/mattermost-preview'
    ports:
      - '8065:8065'
    volumes:
      - ./saipraneeth:/volume
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       hostname
       echo $PWD
       ls
       cat docker-entry.sh
       echo "---- LS /"
       ls /
       echo "-----LS /VOLUME"
       ls /volume/
       echo "----- FIND /VOLUME"
       find /volume
       
