---
version: "3"

services:
  mattermost:
    image: 'mattermost/mattermost-preview'
    ports:
      - '8065:8065'
    volumes:
      - ${PWD}/volume:/volume
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       hostname
       echo $PWD
       ls
       
